name: Build

on:
  push:
    branches:
      - main


jobs:
  sonar:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for SonarQube to be ready
        run: |
          until curl -s http://localhost:9000/api/system/health | grep -q '"status":"UP"'; do
            echo "Waiting for SonarQube..."
            sleep 5
          done
          echo "SonarQube is up!"

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "http://localhost:9000"

